train:
  data_dir: '.'
  # if this file is project/config/default.yaml, 
  # then working dir is project, 
  # and ckpt_dir is project/ckpt_dir
  ckpt_dir: 'ckpt_dir/ablation' 
  batch_size: 8
  num_workers: 0
  max_epoch: 4
  device: 'cuda:0'
  learning_rate: 0.0006
  # alpha: [0.8, 1, 1.1, 0.7, 1.5]
  alpha: [1,1,1,3,1.5]
model:
  num_classes: 5
  image_size: [3, 512, 512]
# name: model-5-classes-ablation-0
name: model-5-classes-ablation-2